name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  TARGET_FOLDER: 
    description: 'target to copy to'
    required: true
  SOURCE_FOLDER: 
    description: 'source to copy from'
    required: true
  CONTENTS:
    description: 'filter options'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.TARGET_FOLDER }}
    - ${{ inputs.SOURCE_FOLDER }}
    - ${{ inputs.CONTENTS }}
