name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  TARGET_FOLDER: ""
  SOURCE_FOLDER: ""
  CONTENTS: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.TARGET_FOLDER }}
    - ${{ inputs.SOURCE_FOLDER }}
    - ${{ inputs.CONTENTS }}
